export const REGION_ORDER: string[] = [
  // Base game
  'Limgrave',
  'Liurnia of the Lakes',
  'Caelid',
  'Siofra River',
  'Ainsel River',
  'Lake of Rot',
  'Nokron, Eternal City',
  'Mt. Gelmir',
  'Altus Plateau',
  'Leyndell, Royal Capital',
  'Forbidden Lands',
  'Mountaintops of the Giants',
  'Consecrated Snowfield',
  'Crumbling Farum Azula',
  'Leyndell, Ashen Capital',
  'Deeproot Depths',
  'Mohgwyn Palace',
  "Miquella's Haligtree",

  // DLC
  'Gravesite Plain',
  'Scadu Altus',
  'Abyssal Woods',
  'Ancient Ruins of Rauh',
  'Rauh Base',
  'Jagged Peak',
  'Scaduview',
  'Cerulean Coast',
  'Shadow Keep',
  "Charo's Hidden Grave",
  'Enir-Ilim',
]
