name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Check licenses
        run: npx license-checker-rseidelsohn --production --onlyAllow "MIT;Apache-2.0;BSD-2-Clause;BSD-3-Clause;ISC;0BSD;CC0-1.0" --excludePackages="lightningcss-darwin-arm64;lightningcss"

      - name: Format check
        run: npm run format:check

      - name: ESLint
        run: npm run lint

      - name: Typecheck
        run: npm run type-check

      - name: Run tests
        run: npm run test:unit

      - name: Build
        run: npm run build
