name: Publish to GitHub Pages

on:
  release:
    types: [published]

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Check licenses
        run: npx license-checker-rseidelsohn --production --onlyAllow "MIT;Apache-2.0;BSD-2-Clause;BSD-3-Clause;ISC;0BSD;CC0-1.0" --excludePackages="lightningcss;lightningcss-android-arm64;lightningcss-darwin-arm64;lightningcss-darwin-x64;lightningcss-freebsd-x64;lightningcss-linux-arm-gnueabihf;lightningcss-linux-arm64-gnu;lightningcss-linux-arm64-musl;lightningcss-linux-x64-gnu;lightningcss-linux-x64-musl;lightningcss-win32-arm64-msvc;lightningcss-win32-x64-msvc"

      - name: Format check
        run: npm run format:check

      - name: ESLint
        run: npm run lint

      - name: Typecheck
        run: npm run type-check

      - name: Run tests
        run: npm run test:unit

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: dist/

  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    needs: build

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5